### ISSUE TITLE
Add license and copyright information

### ISSUE THREAD

**Issue by senotrusov** [amatsuda/kaminari_themes#53]
Please add license and copyright information for the themes.

Thank you!

**Comment by kboygit** [comment]
is this theme free open-source and free of license or what? This is a good kaminari theme

**Comment by yuki24** [comment]
I'm sorry for not getting back sooner, but I'm 99% sure that MIT is the license we'd like to incorporate to this repo.

@amatsuda Any objections?

**Comment by fwolfst** [comment]
This should be cleared before too many more contributions come in ...

**Comment by yuki24** [comment]
This is now in my todo list and I'll come back in March.

**Comment by amatsuda** [comment]
Oops, sorry guys. Just pushed the MIT declaration 😉
